name: Release Docs

on:
  push:
    tags:
      - "v*"

permissions: {}
jobs:
  release_docs:
    permissions:
      contents: write  #  for mike to push

    name: Release Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "./docs/scripts/requirements.txt"

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - run: |
          pip install -r docs/scripts/requirements.txt

      - name: setup
        run: |
          ./docs/scripts/copy_docs.sh
          go run ./docs/scripts/docs.go

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: build and push
        run: |
          mike deploy ${{ github.ref_name }} latest --push --update-aliases
          mike set-default --push latest
